on:
  push:
  pull_request:
    types: [opened, edited]
name: "c-valgrind"
jobs:
  build:
    name: Testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          #- os: windows-2022
          #- os: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Rust Nightly
        run: |
          rustup default nightly
          rustup update

      - name: Install valgrind
        run: sudo apt install -y valgrind

      - name: Valgrind Test
        run: |
          cd core
          make valgrind
